- name: This is for web servers
  hosts: web
  tasks:
    - name:Running copy task
      copy:
        src: /etc/passwd
        dest: /tmp
        owner: root
        mode: 753
    - name:Running file creation task
      file:
        path: /tmp/ansible
        state: directory
- name: This is for app servers
  hosts: app
  tasks:
   - name:Running yum module task
     yum:
        name: httpd
        state: latest
   - name:Running service task
     service:
        name: httpd
        state: started

