- hosts: web
  tasks:
    - copy:
        src: /etc/passwd
        dest: /tmp
        owner: root
        mode: 753
    - file:
        path: /tmp/ansible
        state: directory
- hosts: app
  tasks:
    - yum:
        name: httpd
        state: latest
    - service:
        name: httpd
        state: started

