parameters:
- name: System
  displayName: 'The target stack for deployment'
  type: string
- name: Environment
  displayName: 'The target environment for deployment'
  type: string
- name: VariableGroup
  displayName: 'The name of the variable group holding information for the infra provisioner sp'
  type: string

variables:
- group: wholeview.database.dev.config  # Fetches values like 'Application' and 'RoleID'
- name: BuildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'Release'

jobs:
- job: build_dacpac
  displayName: Build, Certify, and Publish DACPAC
  pool:
    vmImage: 'windows-latest'

  steps:
    - script: |
        echo "Using Application: $(Application)"
        echo "Using RoleID: $(RoleID)"
      displayName: 'Fetch and Display Variable Values'

    - task: VSBuild@1
      displayName: 'SQL Database Project Build'
      inputs:
        solution: '**/*.sqlproj'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'

    - task: GlapiHeadlessBuild@1
      displayName: 'Greenlight Api: Certifies a Build'
      enabled: true
      inputs:
        GreenlightApiConnection: 'Greenlight Api - Prod'
        FailOnGlapiRejection: false
        # Example of using variable values in the inputs
        AdditionalParameter: '$(Application)-$(RoleID)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: WholeviewDatabase'
      inputs:
        PathtoPublish: '$(Build.StagingDirectory)'
        ArtifactName: WholeviewDatabase
