#Definig varaible in inventory file
#can you give different variables value to different hosts in same file
#FIRST METHOD => But lengthy
- hosts: web
  vars: 
    mydir: /tmp/sudharshanam
    myfile: /etc/passwd
    mypkg: 
      - httpd
      - nfs-utils
      - tree 
      - samba 
  tasks:  
    - name: "This task will create a directory name of {{ mydir }}"
      file: 
        path: "{{ mydir }}"
        state: directory 
    - copy:
        src: "{{ myfile }}"
        dest: "{{ mydir }}"
    - yum:
        name: "{{ mypkg }}"
        state: latest 
---
- hosts: app
  vars: 
    mydir: /tmp/kumar
    myfile: /etc/shadow
    mypkg: 
      - apache2 
      - net-tools
      - cowsay
      - smtp 
  tasks:  
    - name: "This task will create a directory name of {{ mydir }}"
      file: 
        path: "{{ mydir }}"
        state: directory 
    - copy:
        src: "{{ myfile }}"
        dest: "{{ mydir }}"
    - yum:
        name: "{{ mypkg }}"
        state: latest 
---
#So we add it in the inventory file right next to the hosts ip 

#[all]
#192.168.1.4 mydir=/tmp/sudharshanam  myfile=/etc/passwd mypkg=httpd,nfs-utils,tree,samba
#192.168.1.5 mydir=/tmp/kumar myfile=/etc/shadow mypkg=tree,docker,net-tools,smtp
hosts: all 
tasks:  
  - name: "This task will create a directory name of {{ mydir }}"
    file: 
      path: "{{ mydir }}"
      state: directory 
  - copy:
      src: "{{ myfile }}"
      dest: "{{ mydir }}"
  - yum:
      name: "{{ mypkg }}"
      state: latest 
